name: Allure Report

on:
  push:
    branches: [ main, master ] # запускать при пуше в эти ветки
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write # разрешаем запись в репозиторий для публикации отчета

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18' # Нужно поставить 18, как в вашем проекте
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests
        run: mvn clean verify
        continue-on-error: true # важно: идем дальше, даже если тесты упали

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report Action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: "target/allure-results"
          allure_history: "allure-history"
          keep_reports: 50

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: "allure-history"
